### ISSUE TITLE
What's the future of this Project ?

### ISSUE THREAD

**Issue by crsmillan** [sheharyarn/dbfs#1]
I found this repo reading https://sheharyar.me/blog/writing-blockchain-elixir/
as a implementation for an MVP.

What's next?
This will be a certain kind of Framework/Library or just a personal project ?

Btw, great job buddy.

**Comment by sheharyarn** [comment]
This is just a personal project and a blockchain experiment in Elixir. I make minor changes from time to time, but no plans on turning this into a full-fledged publishable application or framework.

You should check out the amazing [CoinCoin](https://github.com/robinmonjo/coincoin) project by @robinmonjo though.
