### ISSUE TITLE
yarn installation error

### ISSUE THREAD

**Issue by vinith2002** [sheharyarn/dbfs#2]
![Screenshot (13)](https://user-images.githubusercontent.com/79247675/145704024-da567510-5f4d-4ede-844f-9483707865f1.png)
getting error F:\dbfs-web\node_modules\node-sass: Command failed. error while installing 'yarn' please help me with this step

**Comment by sheharyarn** [comment]
This is an issue with your local `node-sass` installation and not relevant to the `dbfs` project. A quick google search will reveal many solutions to get this working.
